Revert "Simplify the bootstrap script"
This reverts commit 96c304bffb630f32150d0473b06bdb8c9d6f7e8c.

There's a chicken-egg problem with aclocal that prevents autoreconf from
piecing everything together.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -7,12 +7,25 @@
 set -e
 set -u
 
+WORK_DIR="$PWD"
 ROOT_DIR="$(dirname "$0")"
 
 test -n "$ROOT_DIR"
+cd "$ROOT_DIR"
 
-autoreconf -i "$ROOT_DIR"
+if ! command -v libtoolize >/dev/null
+then
+	echo "libtoolize: command not found, falling back to glibtoolize" >&2
+	alias libtoolize=glibtoolize
+fi
 
+aclocal -I .
+libtoolize --copy --force
+autoheader
+automake --add-missing --copy --foreign
+autoconf
+
+cd "$WORK_DIR"
 "$ROOT_DIR"/configure \
 	--enable-silent-rules \
 	--enable-warnings \
